name = "cw721-dapp"

gas_price = '0.025uaura'
gas_adjustment = 1.3
account_prefix = 'aura'
derivation_path = '''m/44'/118'/0'/0/0'''

[networks.testnet]
chain_id = 'osmo-test-4'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc-test.osmosis.zone:443'
rpc_endpoint = 'https://rpc-test.osmosis.zone'

[networks.serenity]
chain_id = 'serenity-testnet-001'
network_variant = 'Shared'
grpc_endpoint = 'https://grpc.serenity.aura.network:9092'
rpc_endpoint = 'https://rpc.serenity.aura.network'

[accounts.aloha]
mnemonic = 'your mnemonic'